---
title: "Class6 R Functions"
author: "Cassandra Wang"
date: "10/17/2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# This is H1
This is my work from class6 in **BIMM143**.

```{r}
# This is to demo a code chunk. 
plot(1:10)
```

## Practice reading files 
```{r}
read.table("test1.txt", sep = ",", header = TRUE)

read.table("test2.txt", sep = "$", header = TRUE)

read.table("test3.txt", sep = "\t")
```

## Working with functions
```{r}
add <- function(x, y=1) {
 # Sum the input x and y
 x + y
}
```

```{r}
add(1)
add(5,5)

add(x=1, y=4)
add(1, 4)
add(1)

# function with vector 
add( c(1, 2, 3) )
add( c(1, 2, 3), 4 )
```

A new function to re-scale data
```{r}
rescale <- function(x) {
 rng <-range(x)
 (x - rng[1]) / (rng[2] - rng[1])
}
```

```{r}
rescale(1:10)
```

```{r}
x <- c(1,2,NA,3,10)
rng <- range(x, na.rm = TRUE)
rng
```

```{r}
rescale2 <- function(x) {
 rng <-range(x, na.rm = TRUE)
 (x - rng[1]) / (rng[2] - rng[1])
}
```

```{r}
rescale2( c(1,2,NA,3,10))
```

```{r}
rescale3 <- function(x, na.rm=TRUE, plot=FALSE) {
  
 rng <-range(x, na.rm=na.rm)
 print("Hello")
 
 answer <- (x - rng[1]) / (rng[2] - rng[1])
 
# return(answer) would end it here

 print("is it me you are looking for?")
 if(plot) {
 plot(answer, typ="b", lwd=4)
 }
 print("I can see it in ...")
}
```

```{r}
rescale3(1:10)
```

# Section2 of hands-on worksheet

Install the **bio3d** package for sequence and structure analysis. 
# install.packages("bio3d")
```{r}
library(bio3d)
s1 <- read.pdb("4AKE") # kinase with drug
s2 <- read.pdb("1AKE") # kinase no drug
s3 <- read.pdb("1E4Y") # kinase with drug

s1.chainA <- trim.pdb(s1, chain="A", elety="CA")
s2.chainA <- trim.pdb(s2, chain="A", elety="CA")
s3.chainA <- trim.pdb(s3, chain="A", elety="CA")

s1.b <- s1.chainA$atom$b
s2.b <- s2.chainA$atom$b
s3.b <- s3.chainA$atom$b

plotb3(s1.b, sse=s1.chainA, typ="l", ylab="Bfactor")
plotb3(s2.b, sse=s2.chainA, typ="l", ylab="Bfactor")
plotb3(s3.b, sse=s3.chainA, typ="l", ylab="Bfactor")
```

```{r}
hc <- hclust( dist( rbind(s1.b, s2.b, s3.b) ) )
plot(hc)
```
